### ISSUE TITLE
[Feedback] how does publish work?

### ISSUE THREAD

**Issue by cyrfer** [aws-amplify/docs#1761]
**Page**: [`/start/getting-started/hosting/q/integration/react`](https://docs.amplify.aws/start/getting-started/hosting/q/integration/react#publish-your-app)

**Feedback**:

It would be great if you could describe a little more what `amplify publish` does behind the scenes.

I am wondering how to get the build to use `.env` files. I want to store environment specific configurations there, but I don't know how to get `amplify publish` to use them.

**Comment by swaminator** [comment]
@cyrfer are you using continuous deployment or manual deployment?

**Comment by mauerbac** [comment]
hey @cyrfer - It sounds like you are curious how `publish` works under the hood? You can look in [here](https://github.com/aws-amplify/amplify-cli/blob/9fead0e8b981a4d32b46bcf0c90cff88d16c5e70/packages/amplify-cli/src/commands/publish.js) in our CLI repo. 

Also, it sounds like you want to understand how to supply environment variables for `amplify add hosting` via the CLI rather than Amplify console?

**Comment by cyrfer** [comment]
Yes. I did find a technique that is working, but I'm not sure if there are any negative consequences.

1. I add configurations for ALL my environments in keys of an object named after the environments.
2. access the key from config object via a single environment variable, REACT_APP_BUILD_ENV.
3. supply `REACT_APP_BUILD_ENV` when `amplify publish` executes the `build` script like this:
```json
"build": "REACT_APP_BUILD_ENV=$(cat amplify/.config/local-env-info.json | jq -r '.envName') react-scripts build",
```
