### ISSUE TITLE
[Feedback] Datastore does not start synching with the cloud until operation is taken

### ISSUE THREAD

**Issue by onlybakam** [aws-amplify/docs#1795]
**Page**: [`/lib/datastore/sync/q/platform/js`](https://docs.amplify.aws/lib/datastore/sync/q/platform/js)

**Feedback**:

the page insinuates that simply following instructions will start synching data with the AppSync backend. that is not correct. synching only starts after an op is done: 

https://github.com/aws-amplify/amplify-js/blob/e71fee58bdd940f5fbcd4268f08f53e2b85168bd/packages/datastore/src/datastore/datastore.ts#L798

really important distinction for customers building multi screen applications and/or components started dynamically.

**Comment by swaminator** [comment]
@onlybakam "synching only starts after an op is done" What do you mean by this? If a developer starts locally, and then runs `npm run amplify-push` that syncs the data the cloud.

**Comment by onlybakam** [comment]
for the client: sync engine is initiated when `start()` is called. `start()` is not called in `configure()`. so unless user does a query/save/observe, no synchronization will happen.

this might sound like an odd thing. but there might be a situation where Amplify is initialized in a top level view/page but no Datastore CRUD operation is taken until user navigates to another view. we should be clear that if you want data to start synching right away, you should call `Datastore.start()`. (the function is now public. it wasnt when i first opened the issue)

**Comment by ericclemmons** [comment]
That's a good point.  Maybe this is a feature request request to improve upon this PR:
> https://github.com/aws-amplify/amplify-js/pull/5942

So the expectation would be kicking off `start()` when DataStore is configured?

**Comment by mauerbac** [comment]
Hi @onlybakam --

I see your concern. Datastore.configure is similar to amplify.configure in that i has the config data which will be used when an API is called. When you use datastore operations like .save(), .query(), .observe() or .remove() the config is used and synced to the backend. Currently, this doesn't happen when .configure is called but rather on an API call due to the amount of data involved -- this can slow an app. Will close this as I believe this is explained. If i'm missing something, please ping this thread.
