### ISSUE TITLE
[amplify mock function] explain `event.json`, `function-parameters.json`, `parameters.json`, `amplify.state` and other autogenerated files

### ISSUE THREAD

**Issue by sw-yx** [aws-amplify/docs#1939]
**Is your feature request related to a problem? Please describe.**

inside https://docs.amplify.aws/cli/usage/mock#function-mocking-setup there is a mention of `event.json`. this is extremely prominent in the CLI workflow:

![image](https://user-images.githubusercontent.com/6764957/84195465-34dce500-aad1-11ea-8cf6-ccb7e77fc367.png)

and as a new user i have no idea what this thing is. and if 99% of the time i dont need to change it, why am i being asked it?

**Describe the solution you'd like**

i'd like the docs to document all autogenerated files like `event.json`, and if the majority of the time `event.json` is colocated or doesn't change, make the file itself optional (best) or warn instead of ask (second best) or explain the file when you ask (third best)

**Comment by TomFrost** [comment]
I landed here from google wondering the same thing, searching `amplify "function-parameters.json"`. This issue was the top result. There are a total of 13 results, and amplify docs aren't one of them.

I am digging amplify in a big way, but the biggest issue by far right now is thoroughness of documentation. We desperately need to be able to understand the configuration files that exist in our own projects.

**Comment by ianmartorell** [comment]
Same here, I'm trying to understand how `parameters.json`, `function-parameters.json` and `team-provider-info.json` work together and I can't find any documentation on this. 😕

**Comment by edwardfoyle** [comment]
The above PR adds a "Files and Folders" reference page in the docs that provides information on the various files created by Amplify.

In regard to mock prompting for the event filename each time, I also added docs around `amplify mock function <func name> --event path/to/event.json which can be used to avoid the prompt.
