### ISSUE TITLE
[Feedback]App Crashes on Launch

### ISSUE THREAD

**Issue by kwomackcodes** [aws-amplify/docs#1988]
**Page**: [`/lib/datastore/getting-started/q/platform/ios`](https://docs.amplify.aws/lib/datastore/getting-started/q/platform/ios)

**Feedback**:

Following the tutorial as is leads to an Amplify Configuration error:

`Failed to initialize Amplify with APIError: No plugin has been added for 'awsAPIPlugin'.
Recovery suggestion: Either add a plugin for 'awsAPIPlugin', or use one of the known keys: `

Adding the following line to the AppDelegate function before the configuration statement fixed the issue for me:

`try Amplify.add(plugin: AWSAPIPlugin(modelRegistration: AmplifyModels()))`

**Comment by mauerbac** [comment]
Thanks for bringing this to our attention @kwomackcodes. @drochetti , can someone on your team verify this?

**Comment by drochetti** [comment]
@kwomackcodes once you add an API (i.e. the API plugin configuration is present in `amplifyconfiguration.json`) the `Amplify.configure()` call validates if a plugin was added for that configuration.

We already relaxed that validation and it will be part of the `1.0.2` release coming real soon.

I believe if you strictly follow the tutorial steps you should have the API plugin in place so that error won't occur. Are you able to confirm if that's the case?

**Comment by kwomackcodes** [comment]
Hi @drochetti!

I think understand what you mean. I followed the [Project Setup](https://docs.amplify.aws/lib/project-setup/prereq/q/platform/ios#initialization) steps from the documentation and then skipped to the [Getting Started](https://docs.amplify.aws/lib/datastore/getting-started/q/platform/ios) page for Datastore. 

The Podfile on the Datastore page includes a pod for 'AmplifyPlugins/AWSAPIPlugin', but then that plugin is not added in the `application:didFinishLaunchingWithOptions`. I think that was the issue with the documentation I followed.

**Comment by drochetti** [comment]
Hey @kwomackcodes, thanks for the clarification.

We're working on an update to the DataStore documentation in this #1906 and it should provide a more consistent guide. In the meantime, using the latest version of Amplify for iOS should fix the configuration error even if the plugin is not added (you will get a warning instead of an error).

If you have any issues with the DataStore functionality, feel free to reach out to us on Discord (https://discord.gg/amplify) or opening an issue in our repo (https://github.com/aws-amplify/amplify-ios).

**Comment by kwomackcodes** [comment]
Thanks @drochetti !
