### ISSUE TITLE
Allow configuring Cognito User Pool auth without using Amplify CLI

### ISSUE THREAD

**Issue by justin-augusto** [aws-amplify/docs#2041]
Many consumers of the aws-amplify libraries are using CDK or CloudFormation directly to provision resources like Cognito User Pools. For these consumers/users Amplify currently requires numerous workarounds, e.g., https://github.com/aws-amplify/amplify-cli/issues/779 to simply use an existing Cognito User Pool for registration and auth use cases. Ideally, one could simply include a configuration file - or better yet, pass configuration parameters to the Amplify.Auth constructor - to begin working with Cognito User Pools through Amplify. Please provide a simple means of configuring Amplify to use existing AWS resources without the need to run `amplify init` and generate numerous "special" files within the target codebase.

**Comment by yuth** [comment]
cc @drochetti

**Comment by devcshort** [comment]
@jtwolgamott not sure if this section is new, but they do have a section for using existing resources without the cli and on ios. It can be found [here](https://docs.amplify.aws/lib/auth/existing-resources/q/platform/ios)

**Comment by drochetti** [comment]
Thanks for providing the link @devcshort. 

@jtwolgamott can you confirm if the content available at https://docs.amplify.aws/lib/auth/existing-resources/q/platform/ios is what you're looking for?

**Comment by jtwolgamott** [comment]
Thanks @devcshort and @drochetti, this is helpful, but it seems to be missing some context, e.g., where should this file be located? Do I need to run `amplify init` to generate this file? If I do need to use `amplify init` to generate the file, does that mean I'll now have an unnecessary, automatically created Cognito User Pool? 

What would be far more helpful would be instructions for configuring Cognito User Pool auth on iOS without using a wizard to create resources, files, config, etc. This still seems very "black box" to me if we are in fact still expecting people to start with `amplify init`.

**Comment by drochetti** [comment]
Thanks for the thoughtful response @jtwolgamott 

> where should this file be located?

Where the config file is located doesn't really matter as long as it's added to your Xcode project. By default `amplify init` creates it at the project root.

> Do I need to run amplify init to generate this file? If I do need to use amplify init to generate the file, does that mean I'll now have an unnecessary, automatically created Cognito User Pool?

You don't need to. You can create an empty JSON file and add your own config.

> What would be far more helpful would be instructions for configuring Cognito User Pool auth on iOS without using a wizard (amplify init) to create resources, files, config, etc. This still seems very "black box" to me if we are in fact still expecting people to start with amplify init.

Point taken and I appreciate the feedback. One of the goals of Amplify is to simplify backend provisioning for developers with no previous AWS and/or backend knowledge. In order to do that Amplify does take an opinionated approach, so we do expect people to start with `amplify init` by default. Taking other routes like CDK is something that we're aware of and we're evaluating adding a CLI functionality to import AWS resources provisioned via console, CDK, etc. Like @yuth mentioned, there's an RFC for that feature, feel free to join the conversation: https://github.com/aws-amplify/amplify-cli/issues/3977

I'll look into clarifying the "Existing resources" docs.
