### ISSUE TITLE
[Feedback]How can I customize the color of loading icon?

### ISSUE THREAD

**Issue by lhmcn** [aws-amplify/docs#2064]
**Page**: [`/ui/q/framework/react`](https://docs.amplify.aws/ui/q/framework/react)

**Feedback**:

I am theming the authenticator and have changed the color of buttons and links with the following css code.

```
:root {
	--amplify-primary-color: #1890ff;
	--amplify-primary-tint: #40a9ff;
	--amplify-primary-shade: #1890ff;
}
```

However, the loading icon is still in the default color.
![screenshot](https://user-images.githubusercontent.com/13793092/86634473-84f77c00-bf97-11ea-9f90-1d87f01467b1.png)

Would you please tell me how I can customize the loading icon? Thanks a lot.

**Comment by wlee221** [comment]
Hi @lhmcn! we're sorry about the delayed response. You can customize the color with
App.css
```
amplify-loading-spinner {
  --spinner-circle-fill: #1890ff;
  --spinner-bar-fill: white;
}
```
to have a blue spinner on top of white circle, for example. We're [working on documenting](https://github.com/aws-amplify/amplify-js/pull/6914) all the components used within our ui, so that these css properties will be clearer. 

Thanks!
