### ISSUE TITLE
[Feedback] Extra symbols in JS API Getting Started Guide -> Build Failure

### ISSUE THREAD

**Issue by kkbava** [aws-amplify/docs#2081]
**Page**: [`/start/getting-started/data-model/q/integration/js`](https://docs.amplify.aws/start/getting-started/data-model/q/integration/js)

**Feedback**:

In the page https://docs.amplify.aws/start/getting-started/data-model/q/integration/js#connect-frontend-to-api the last 2 code snippets have + symbols and @@ symbols. When I copy / pasted this code (say, last snippet) into app.js. npm start gives a ton of errors - until all those symbols are removed. 
Still gives an error on last statement 
getData();

Copy-paste cant lead to errors! :(

**Comment by jamesonwilliams** [comment]
Hmm. Looks like the author of this Getting Started guide used diff syntax a _deliberate_ stylistic choice, to show the user what is being added/removed.

I agree with @kkbava that it's a confusing choice. Many users will want to copy-paste code from the Getting Started guide.

The Getting Started guide for the native libraries uses inline comments, instead of diff annotations.

For example:
```kotlin
// Add this call.
Amplify.API.create(model,
    { Log.d("It worked") },
    { Log.d("It didn't work.") }
)
```
As opposed to:
```kotlin
+ Amplify.API.create(model,
+.    { Log.d("It worked") },
+     { Log.d("It didn't work.") }
+ )
```

For another thing, the diff syntax messes up the code formatting, which is annoying.

**Comment by mauerbac** [comment]
Thanks for taking the time to provide this feedback @kkbava! I agree with @jamesonwilliams - it looks intentional to tell the story. I also agree that it makes it hard to copy and paste. Let me sync with the team and update if it makes sense.
