### ISSUE TITLE
AWS amplify API doc - wrong import

### ISSUE THREAD

**Issue by rpostulart** [aws-amplify/docs#211]
On this page (https://aws-amplify.github.io/docs/js/api) there is a 
import { Connect } from "aws-amplify-react";

But I believe that has to be:
import { Connect } from "aws-amplify-react-native";

At least now my app is working :)

**Comment by YikSanChan** [comment]
The doc doesn't do wrong in this import.

Because both `aws-amplify-react Connect` (https://github.com/aws-amplify/amplify-js/blob/4644b4322e/packages/aws-amplify-react/src/API/GraphQL/Connect.js) and `aws-amplify-react-native Connect` (https://github.com/aws-amplify/amplify-js/blob/4644b4322e/packages/aws-amplify-react-native/src/API/GraphQL/Connect.js) exist.

**Comment by rpostulart** [comment]
Yes but the first import statement gives errors that the module doesn't exist in de Haste module map.

**Comment by YikSanChan** [comment]
You might want to run `yarn add aws-amplify-react`

**Comment by nikhil-dabhade** [comment]
@rpostulart : Were you able to proceed on this?

**Comment by nikhil-dabhade** [comment]
@rpostulart : Following up on this.

**Comment by rpostulart** [comment]
Indeed solved by that yarn add
