### ISSUE TITLE
[Feedback]More detailed or "advanced" documentation for add-graphql-datasource

### ISSUE THREAD

**Issue by cookmscott** [aws-amplify/docs#2431]
**Page**: [`/cli/graphql-transformer/relational`](https://docs.amplify.aws/cli/graphql-transformer/relational#sample)

**Feedback**:

The `amplify add-graphql-datasource` got me started for basic GraphQL queries against my AuroraDB. Unfortunately, I'm not sure where to go from here. It would be great if there were **additional details** on:
* how to update schema.graphql to include `@connections` to reflect table relationships
** maybe adding a second part of the docs to show how to setup/query a customer and their orders (across tables)
** do you need to make custom resolvers?
** if you don't get table relations out of the box, you should not include an example with customers and orders. 
* setting user permissions for resources since `@auth` is not supported

**Comment by mauerbac** [comment]
Thanks @cookmscott - this should be enough info for us to improve the docs. Stay tuned

**Comment by cookmscott** [comment]
Sounds great @mauerbac , I look forward to seeing some additional details! 

Updated docs will certainly be a great first step, but I also think a full blown example would also be very helpful. Currently the AppSync + Aurora sample is archived: https://github.com/amazon-archives/aws-appsync-rds-aurora-sample

**Comment by stayingcool** [comment]
What we have is just the setup to plug the AuroraDB to AppSync. However, if you look at DynamoDB there are tons of documentation for setup, directives (auth, model, connection, etc...), and other advanced features.

It's been 6 months since the support for [AuroraDB](https://aws.amazon.com/about-aws/whats-new/2019/04/aws-amplify-announces-new-amazon-aurora-serverless--graphql--and/) was announced, there is hardly any improvement with functionality and documentation.

I have been testing hasura every time I'm getting blocked on Amplify/AuroraDB. So far hasura seems to be working great with AWS RDS, I'm just reluctant to pick it as it'll add another operational task to keep an eye on! If things don't improve I might just make that decision and save my countless hours of searching for how to do in Amplify/AuroraDB!

**Note:** I do not have any allegiance with any tool/framework. I'm trying to use what is best and easy according to my capabilities and knowledge.

**Comment by idanlo** [comment]
18 months... This is crazy, and they won't even respond here.

**Comment by renebrandel** [comment]
Hi - I'm closing this issue because we're deprecating the existing workflow in favor of a new experience as part of the new GraphQL Transformer. You can follow along our progress in this RFC: https://github.com/aws-amplify/amplify-category-api/issues/815
