### ISSUE TITLE
[Feedback]Unable to Create login UI - TypeError

### ISSUE THREAD

**Issue by LeoSalemann** [aws-amplify/docs#2454]
**Page**: [`/start/getting-started/setup/q/integration/android`](https://docs.amplify.aws/start/getting-started/setup/q/integration/android)

**Feedback**:

Followed procedures in [Create login UI for react native](https://docs.amplify.aws/start/getting-started/auth/q/integration/react-native#create-login-ui), _expo start_  fails.

**Also Note:**  _Page_ says https://docs.amplify.aws/start/getting-started/setup/q/integration/android, but I was actually in _https://docs.amplify.aws/start/getting-started/auth/q/integration/react-native#create-login-ui_

<img width="917" alt="add-auth-pic01" src="https://user-images.githubusercontent.com/6365898/94211601-b8ef8880-fe86-11ea-88d7-ddbd89eb6bc0.png">
<img width="881" alt="add-auth-pic02" src="https://user-images.githubusercontent.com/6365898/94211608-bdb43c80-fe86-11ea-919b-08aef7f254d6.png">

**Comment by aehwany** [comment]
@LeoSalemann 
Hi, I’m currently working on this issue. I followed the procedure in [Create login UI for react native](https://docs.amplify.aws/start/getting-started/auth/q/integration/react-native#create-login-ui) and I wasn’t able to reproduce the fail on running expo start.
Can you please provide more information on the following:
* Can you provide more details on the system/environment you were using (ex: OS)
* I’m wondering if you were trying to setup an Android or React Native project using Amplify. I’m bit confused with the wording, since you mentioned Android, but you’re using the guide for react-native.
* Do you get the following errors in the screenshots when running expo start? The reason Im asking is because these errors are related to React.
* Can you please clarify on the last note you mentioned about wrong pages being displayed?

**Comment by LeoSalemann** [comment]
@aehwany 

- I believe I was running a linux/ubuntu VM in Virtual Box, hosted on a Macbook running OSX 10.15.7
- I was setting up react native.  
- I believe I was suing expo start
- To clarify, I was indeed running the react-native tutorial.  When I ran into trouble and clicked the _We'd Love your feedback_ link, the Page field of the issue got defaulted to :/start/getting-started/setup/q/integration/android when I was actually in /start/getting-started/auth/q/integration/react-native#create-login-ui.

Hope this helps.

**Comment by aehwany** [comment]
@LeoSalemann 
Thanks for your feedback, I'm afraid I still have difficulty reproducing the issue you have encountered.
I followed your steps as specified,and got the following feedback page. As you can see, the path seems right here.


![Screen Shot 2020-10-28 at 3 37 10 PM](https://user-images.githubusercontent.com/25094808/97489626-2aaf6c00-1936-11eb-831b-5c6cfd060f04.png)
