### ISSUE TITLE
Please label web pages with date of last update.

### ISSUE THREAD

**Issue by robotica-labs** [aws-amplify/docs#2489]
**Page**: [`/start/q/integration/ios`](https://docs.amplify.aws/start/q/integration/ios)

**Feedback**:

**Comment by swaminator** [comment]
@robotica-labs what's the usecase?

**Comment by robotica-labs** [comment]
The use case is to determine how old the content is/if it is being maintained.

**Comment by swaminator** [comment]
Thanks that's really useful feedback and we will look into this cc @mauerbac.

**Comment by mauerbac** [comment]
Thanks, I saw this one! Think it is great. acts like a freshness/stale meter. it's in the backlog.

**Comment by mauerbac** [comment]
Keep open

**Comment by medelman17** [comment]
Closing this as a 'Won't Fix'. We'll address this issue with 'versioning'--i.e., where we explicitly state the versions of Amplify libraries, etc., to which given documentation applies. Dating is an anti-pattern whereby one might assume that, because the publication date of a given piece of documentation is old, the documentation is no longer relevant when in fact the API is just stable and 'old' documentation nailed it perfectly.
