### ISSUE TITLE
Add Better Documentation for graphqlOperation

### ISSUE THREAD

**Issue by aspittel** [aws-amplify/docs#2635]
**Is your feature request related to a problem? Please describe.**
Right now, `graphqlOperation` is introduced [here](https://docs.amplify.aws/lib/graphqlapi/getting-started/q/platform/js#enable-queries-mutations-and-subscriptions) and used in our documentation, but isn't further described.

**Describe the solution you'd like**
Add more examples and documentation for `graphqlOperation` including customer written queries and strings rather than just Amplify generated queries. Include why it's needed, what can be passed to it, give multiple examples etc.

**Additional context**
I've gotten multiple customer questions that would be solved by this, and I wanted more documentation on it when I was starting to learn Amplify.

Note: I can take a first attempt at this.

**Comment by sw-yx** [comment]
i've actually been [de-emphasizing it in the docs](https://github.com/aws-amplify/docs/pull/2459) because it isn't very helpful. 

to be clear, this function will be supported for a long time and customers can safely continue using and relying on it. I just dont think you need it and that your code will be more readable without it.

if you look at the source, it is an extremely thin wrapper:

https://github.com/aws-amplify/amplify-js/blob/61f7478609fce7dd2f25c562aeb887d3f3db4a67/packages/api-graphql/src/GraphQLAPI.ts#L35-L38

this is an extra abstraction to teach when using Amplify, and in my opinion isn't really worth it. you dont need this function for writing  customer written queries and strings.

**Comment by aspittel** [comment]
I think in that case we need to remove it from the getting started guide
because customers are getting started using it, wondering how to extend it
or write their own queries, and not finding answers. I’m fine with either
direction, but this has come up indirectly multiple times in the discord
and in 1-1 conversations I’ve had.

**Comment by dabit3** [comment]
I agree with removing `graphqlOperation` from the docs and prefer the other approach.

**Comment by sammartinez** [comment]
As per an offline convo with aspittel, I am goin to close this for now
