### ISSUE TITLE
[Feedback]JWT Auth Request

### ISSUE THREAD

**Issue by sophiagatliff** [aws-amplify/docs#2735]
**Page**: [`/lib/q/platform/ios`](https://docs.amplify.aws/lib/q/platform/ios)

**Feedback**:

Hiya.

I already have an auth flow set up, and I'm really only looking to use AWS S3 Storage for image storage.
Could you add a JWT Authentication option?

Thank you. :)

**Comment by mauerbac** [comment]
Hello @sophiagatliff - are you using the storage category ? You are asking how to use JWT Auth with S3 directly ?

**Comment by sophiagatliff** [comment]
Hi!

Yes I'm using the storage catagory w/ amplify. Sorry for the confusion. 

I'd like to have a JWT option for sign in into Amplify. Would make integrating it into my app possible. Right now I'm using storage w/o auth.

**Comment by ruiguoamz** [comment]
Hi, @sophiagatliff 

This feels like a feature request instead of documentation improvement.

Also, can you be more specific JWT Auth Request. Are you asking something like:
```swift
Amplify.Auth.signIn(jwtOption: JWTOption) {
    // Call back
}
```

We would like to understand more about your request. Thanks

**Comment by palpatim** [comment]
I think what @sophiagatliff is asking for with "JWT Authentication option" is the ability for S3 to accept authorizations via JWT tokens (that is, signing in with only User Pools) rather than requiring AWS Credentials (that is, federating into Identity Pools), is that right?

If so, I'd echo the previous questions: What is the use case you're trying to support with this? Amplify will automatically provision a Cognito Identity Pool that will handle creating credentials for services like S3 that require AWS Credentials for authorization.

In any case, some clarifications would be helpful. :)
