### ISSUE TITLE
[Feedback]Can not find accurate API references for Android 

### ISSUE THREAD

**Issue by mohitb117** [aws-amplify/docs#2775]
**Page**: [`/sdk/q/platform/android`](https://docs.amplify.aws/sdk/q/platform/android)

**Feedback**:

I can't find good references to Mobile Artifacts for Android/iOS SDKs for the AWS Services/Features on Amplify.

Referencing: 
https://aws.amazon.com/blogs/mobile/aws-mobile-sdk-for-android-maven-support/

Any Advice would be greatly appreciated.

**Comment by jamesonwilliams** [comment]
Hi @mohitb117! If you're looking to onboard AWS functionalities into your iOS and Android apps, please see the documentation for [Amplify Android](https://docs.amplify.aws/lib/q/platform/android) and [Amplify iOS](https://docs.amplify.aws/lib/q/platform/ios).

The [blog you're referencing, about newly added Maven support](https://aws.amazon.com/blogs/mobile/aws-mobile-sdk-for-android-maven-support/), is more than six years old. It makes reference to the AWS Mobile SDK for Android. We still do host [documentation for the Mobile SDKs](https://docs.amplify.aws/sdk/q/platform/android), we're just not advertising it much.

You might also be interested to read this StackOverflow discussion: [Will AWS SDK libraries go away due to Amplify?](https://stackoverflow.com/questions/64977896/will-aws-sdk-libraries-go-away-due-to-amplify/64990655#64990655).

Happy hacking. Jameson

**Comment by mohitb117** [comment]
Thank you, this has been helpful 👍
