### ISSUE TITLE
[Feedback]Tutorial doesn't seems to work with Vue3

### ISSUE THREAD

**Issue by modullar** [aws-amplify/docs#2878]
**Page**: [`/start/getting-started/setup/q/integration/vue`](https://docs.amplify.aws/start/getting-started/setup/q/integration/vue)

**Feedback**:

Once I get to the step of [setting up frontend here](https://docs.amplify.aws/start/getting-started/setup/q/integration/vue#set-up-frontend), I get this error when running the server: 
```
Uncaught TypeError: Cannot read property 'config' of undefined
```

The command fails at this line: `Vue.config.ignoredElements = [/amplify-\w*/];` 
Although the syntax in the tutorial seems to be Vue3 syntax.

**Comment by wlee221** [comment]
You are right, the current documentation is based on Vue 2 API. `Vue 3` deprecates default export, so that's why you are seeing that error.

We are working on updating the docs to reflect Vue 3 ([branch](https://github.com/aws-amplify/docs/tree/vue3)). Meanwhile, you can use this https://github.com/aws-amplify/amplify-js/issues/6756#issuecomment-710100373 to set this up.
