### ISSUE TITLE
Link to Flutter guides is broken

### ISSUE THREAD

**Issue by mauerbac** [aws-amplify/docs#2930]
1. Go to https://docs.amplify.aws/guides
2. Click on Flutter

Unable to access the Flutter guides

**Comment by medelman17** [comment]
This appears to be fixed. @mauerbac can you confirm that this issue can be closed?

**Comment by medelman17** [comment]
Closing this as stale and likely remedied recently.

**Comment by tjleing** [comment]
Ah wait, I think I have a little bit more context on this one -- the Flutter link here is supposed to link to https://aws.amazon.com/getting-started/hands-on/build-flutter-app-amplify/ which is currently down and redirecting back to the Flutter docs on the Amplify website.  Those docs are down due to some updates, so until they're back up, this is intended.
