### ISSUE TITLE
Update Github command to push to 'main' instead of 'master'

### ISSUE THREAD

**Issue by hritesh93** [aws-amplify/docs#2979]
**Describe the bug**
Default GitHub repo is now 'main'
The GitHub command: 'git push origin master' is now changed to 'git push -u origin main'
This outdated default branch push will create a new branch and will commit to the newly created 'master' branch

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://aws.amazon.com/getting-started/hands-on/build-react-app-amplify-graphql/module-three/?e=gs2020&p=build-a-react-app-two'
2. Scroll down to 'Deploy changes to live environment'
3. See error

**Additional context**
Also the 'setup for CI/CD of frontend and backend' section is giving build failure.
Do resolve the documentation at the earliest for a proper workflow.

**Comment by medelman17** [comment]
Agree as a general matter that we should conform our documentation to the new GH 'main instead of master' convention. Unfortunately, in this specific instance, I don't believe that we control the content referenced above. @mauerbac, can you confirm? 

I am going to close this issue, and will open a new one re doing the 'master' to 'main' migration generally. 

Re: the CI/CD failure bit mentioned in the context section above, it's probably worth breaking out into a spectate issue so that the discussion doesn't get muddled, here. 

@hritesh93, can you open a new issue dedicated to the CI/CD issue specifically and expound greatly on what's happening so that we can reproduce?
