### ISSUE TITLE
Extra code blocks showing sometimes

### ISSUE THREAD

**Issue by tjleing** [aws-amplify/docs#3091]
**Describe the bug**
On some pages, more than one language's code blocks are rendering, one after the other.  Thanks for the callout @drochetti and @ericclemmons!

**To Reproduce**
Go to [this link](https://docs.amplify.aws/lib/analytics/identifyuser/q/platform/android).  Pick RxJava.  Refresh.

**Screenshots**
![image](https://user-images.githubusercontent.com/9170787/113029802-df0a2400-915a-11eb-9ab7-b4ccb44b2a34.png)

**Additional context**
Still looking at the DOM and CSS, but it doesn't quite look like the same `<slot>` issue as #3079.  Will link PR when created.

**Comment by tjleing** [comment]
Issue found: somehow two CSS fragments are both being applied: one from the pre-rendering process, and one from the hydration process.  The pre-rendering fragment selects `:nth-of-type(1)` to be visible because the initial language framework is visible by default.  However, when we load the actually selected framework from the cookie, we want `:nth-of-type(3)` to be visible -- and in fact, it is.

Really not sure why both fragments are being attached.  Seems like a Stencil bug.

**Comment by tjleing** [comment]
Connected to https://github.com/ionic-team/stencil/issues/2871 as the root cause.  Not entirely sure how to work around the issue in the meantime, other than writing really hacky code to parse the DOM and literally only have one code block even existing at a given time.

**Comment by medelman17** [comment]
Do we have an understanding re: how prevalent this issue is? In other words, of the total pages that include the above, how many are rendering inappropriately? To the extent that (1) the prevalence is low and (2) migrating to NextJS would solve the issue, we might consider this a 'Won't Fix' for the time being. I don't like the idea of spending time/resources writing really hack-y code, especially if we're going to delete it ASAP.

**Comment by tjleing** [comment]
I just tried it on some other pages, and it seems like it's 100% prevalence, but in a use case that fairly few users will actually run into.  Most page accesses aren't hitting pages with multiple code blocks, and the problem only occurs on the first page of a user's visit (when first clicking a link into the site, or refreshing, etc.).

The migration to NextJS will absolutely solve the issue.  Making this one a 'won't fix' could make sense given these facts, but I might consider leaving it open because of the possibility that Stencil can fix the underlying issue quickly.

**Comment by ericclemmons** [comment]
I've also experienced it on Amplify Admin UI, which has web components (based on `awsui-tabs`):
> ![Screen Shot 2021-04-01 at 11 44 10 AM](https://user-images.githubusercontent.com/15182/113326719-e6523e80-92ce-11eb-9942-83feb0c0c43f.png)

**Comment by medelman17** [comment]
This issue is almost certainly arising as a consequence of the pre-rendering process. Specifically, the `BlockSwitcher` component relies on an array of `selectedTabHeadings` (e.g., `["kotlin", "java", "fortran"]`) to determine if a non-default code block should be displayed initially. Crucially, the value of this property is derived/populated from browser local storage, which, obviously, does not exist when the website is pre-rendering. As a result, the default is always set to be displayed initially and is pre-rendered as expected. For whatever reason, when the client rehydrates, looks at the newly populated `selectedTabHeadings` array, and determines that a non-default block should be shown, the pre-rendered default block is not re-rendered/updated. As a result, both are shown.  

Notably, this issue only occurs on initial entry. Thereafter, when navigating between pages from within the website, code blocks all work as expected. Moreover, the issue only arises where a user has previously selected a `tabHeading`. Disabling pre-rendering for the `BlockSwitcher` component in `prerender.config.js` fully resolves the issue. Unfortunately, doing so creates another issue wherein there's a notable screen flash/shift. 

If this were a React-based website, the solution would be rather trivial: rather than render all children code blocks and toggle the visibility thereof using css display property, one would just render the single code block that corresponds to `activeChild`--no more, no less.
