### ISSUE TITLE
[Feedback] Angular Authentication Instructions not working

### ISSUE THREAD

**Issue by Hercast** [aws-amplify/docs#3286]
**Page**: [`/start/getting-started/auth/q/integration/angular`](https://docs.amplify.aws/start/getting-started/auth/q/integration/angular)

**Feedback**:

The showed method in the getting started section to add Authentication to the amplify app ([here](https://docs.amplify.aws/start/getting-started/auth/q/integration/angular)) does not work or is missing some specific instructions. After following all the described steps an error appears while testing the Login UI > *Authentication Error*

In browser Console:

Error: Amplify has not been configured correctly.
            This error is typically caused by one of the following scenarios:

            1. Make sure you're passing the awsconfig object to Amplify.configure() in your app's entry point
                See https://aws-amplify.github.io/docs/js/authentication#configure-your-app for more information
            
            2. There might be multiple conflicting versions of aws-amplify or amplify packages in your node_modules.
                Try deleting your node_modules folder and reinstalling the dependencies with `yarn install`

However, by using the instructions here (https://docs.amplify.aws/start/getting-started/auth/q/integration/angular ) and here ( https://medium.com/workfall/how-to-build-an-angular-authentication-application-using-aws-amplify-3cdc6e67cfc2) certainly works.

**Comment by wlee221** [comment]
Hello @Hercast, thanks for raising this issue!

The error you provided usually happens when you have a mistmatching Amplify package versions. Can you try the [troubleshooting guide](https://docs.amplify.aws/lib/troubleshooting/upgrading/q/platform/js/) we have for this and see if this resolves it? Specifically the "Upgrade Amplify packages" section will be useful for addressing this error. Please let us know if you still have the same issue.
