### ISSUE TITLE
[Feedback]Document for vue seems out of date

### ISSUE THREAD

**Issue by peebles** [aws-amplify/docs#3294]
**Page**: [`/ui/auth/authenticator/q/framework/vue`](https://docs.amplify.aws/ui/auth/authenticator/q/framework/vue)

**Feedback**:

This document talks about slots quite a bit, but the aws-amplify-vue code base, version 2.1.5 does not make any use of slots.

**Comment by ErikCH** [comment]
Hello @peebles !

Thanks for bringing this up. In our documentation for Vue we have two tabs. One for latest, which is our `@aws-amplify/ui-components` and `@aws-amplify/ui-vue` for Vue 3 and Vue 2 libraries respectively. We also have our legacy library which is for the `aws-amplify-vue`. 

After clicking on legacy, there are some usage of scoped slots in the [connect API](https://docs.amplify.aws/ui-legacy/api/connect/q/framework/vue/#sign-upin-with-emailphone-number). Otherwise most of the `aws-amplify-vue` library relies on props and a Amplify Event Bus.

If you looking to do full customization of your Vue application, I would recommend using the latest Vue libraries for `@aws-amplify/ui-components` or `@aws-amplify/ui-vue`. 

It's worth mentioning that we'll have a new Vue 3 version of the UI library out soon that should have a [preview release](https://github.com/aws-amplify/amplify-ui) in October.

**Comment by ErikCH** [comment]
Going to close the issue for now
