### ISSUE TITLE
[Feedback] federated prop documentation incorrect

### ISSUE THREAD

**Issue by lack-of-gravitas** [aws-amplify/docs#3431]
**Page**: [`/ui/auth/authenticator/q/framework/react`](https://docs.amplify.aws/ui/auth/authenticator/q/framework/react)

**Feedback**:
the federated prop appears to apply at <AmplifySIgnIn and not at <AmplifyAuthenticator as indicated in the documentation. Tested just now with a hello world implementation

1 - please update your documentation or hell have documentation that can be understood
2 - don't release components without disclaimers or make it clear that ymmv / documentation is not available so we dont invest in building business critical apps with supposedly "pre-built" components
3 - please think of the noobs (like me) who have to trawl through issues like [this](https://github.com/aws-amplify/amplify-js/issues/7199) or [this](https://github.com/aws-amplify/amplify-js/discussions/8161) which suggest using css query selectors to remove buttons that clearly are not enabled by default.

![image](https://user-images.githubusercontent.com/10094964/127502197-023c99d0-c237-4415-92a0-9478ed88bac2.png)

![image](https://user-images.githubusercontent.com/10094964/127502546-5446ebf1-664b-434a-955e-93145a5dcdd7.png)

**Comment by josefaidt** [comment]
Hey @lack-of-gravitas :wave: the new UI components have since released and are on a new site https://ui.docs.amplify.aws/components/authenticator#zero-configuration, where the authenticator is now zero-config! We can also use the `socialProviders` prop to customize whether we display certain providers https://ui.docs.amplify.aws/components/authenticator#social-providers

Closing issue 🙂
