### ISSUE TITLE
[Feedback] If renaming aws-exports.js to aws-exports.ts

### ISSUE THREAD

**Issue by rolance** [aws-amplify/docs#3611]
**Page**: [`/start/getting-started/data-model/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/data-model/q/integration/angular/#connect-frontend-to-api)

**Feedback**:  If you rename  "aws-exports.js" to "aws-exports.ts", the contents of the former have to be copied to the latter following changes to amplify configuration. This should probably be mentioned in subsequent pages (ie on adding auth and hosting).

**Comment by josefaidt** [comment]
Hey @rolance :wave: thanks for raising this! Unfortunately this is the expected behavior, however there is [an open feature request with the CLI](https://github.com/aws-amplify/amplify-cli/issues/304) to generate TypeScript aws-exports file. Thankfully in TypeScript we can import JavaScript files, though I understand the want for having .ts files. Would you mind adding your notes/use case to the existing feature request?
