### ISSUE TITLE
Doc entries are split between the CLI and the library

### ISSUE THREAD

**Issue by DylanBruzenak** [aws-amplify/docs#3865]
**Describe the bug**
Currently there are two different sets of documentation that cover the same topics. The cli link at the top of the docs page: https://docs.amplify.aws/cli/ and the libraries, for example js: https://docs.amplify.aws/lib/q/platform/js/.

If you expand, for example, the graphql section of the JS library doc it is missing important entries from the cli, such as "custom business logic.

**To Reproduce**
1. Go to https://docs.amplify.aws/cli/ and https://docs.amplify.aws/cli/ and https://docs.amplify.aws/lib/q/platform/js/
2. expand API (GraphQL) on the left on each page
3. Note that the entries are different and to get a complete view of the capabilities both have to be read.

**Expected behavior**
I would expect that clicking through to the doc for the library I use would provide a comprehensive overview of the provided services. 

**Screenshots**
![Screen Shot 2021-12-10 at 12 21 59 PM](https://user-images.githubusercontent.com/60181/145622947-2923cfa0-bc50-4187-af18-ab9e8b613e7a.png)
![Screen Shot 2021-12-10 at 12 22 15 PM](https://user-images.githubusercontent.com/60181/145622958-0f999317-1e40-4d83-851b-70a1fd76c030.png)

**Desktop (please complete the following information):**
 - OS: MacOS 12
 - Browser Safari
 - Version 15.0

**Comment by nadetastic** [comment]
Hi @DylanBruzenak 👋,

The reason for this setup is each guide has sections that are relevant to the library/tool. In addition to the CLI and JS guides, the other libraries such as Swift and Android etc also have the same setup. In order to use Amplify as a whole, you would need to reference each guide for specifics.

We appreciate the feedback, and if you have additional comments please let us know.
