### ISSUE TITLE
Permission Boundary by environment example

### ISSUE THREAD

**Issue by fooman** [aws-amplify/docs#4042]
**Is your feature request related to a problem? Please describe.**
It would be great to have an example of how permission boundaries work when restricting by Amplify environments. It looks like [this feedback](https://github.com/aws-amplify/docs/pull/3157#discussion_r618049919) didn't make it into the final version. So far all mentions of permission boundaries are relating to company policies but none describe how the amplify environment can be considered.

**Describe the solution you'd like**
An example IAM policy restricting Amplify environments.

Links 
https://docs.amplify.aws/cli/project/permissions-boundary/
https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html
https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html

**Comment by justinwiley** [comment]
Is it possible to increase the urgency of this feature request?  The sole AWS managed policy 'AdministratorAccess-Amplify' allows very broad access, and the IAM documentation while extensive largely seems to devolve to  "Administrators can use AWS JSON policies to specify who has access to what."

So by default, unless Amplify is operating in complete account-level isolation or in a hobby projects, it's very difficult to use safely without permissions boundaries.  And without some sort of example (or better set of examples), it's hard for folks new to Amplify, or security administrators who shouldn't need to exhaustively understand every possible feature, to get started in medium to large-scale environments.  This includes the 'confused deputy' related guidance, which is again structured as an add-on with limited guidance instead of a core concern.

**Comment by ykethan** [comment]
Closing the issue as the PR has been merged. https://github.com/aws-amplify/docs/pull/5113
