### ISSUE TITLE
[Feedback]Does "delete" data really "delete" it?

### ISSUE THREAD

**Issue by guplem** [aws-amplify/docs#4098]
**Page**: [`/console/data/content-management`](https://docs.amplify.aws/console/data/content-management/#to-create-and-link-data)

**Feedback**:

As you can see in [here](https://github.com/aws-amplify/amplify-flutter/issues/496#issuecomment-814619989), the data doesn't seem to be 100% deleted after using Amplify.DataStore.delete.

That should be noted and maybe a way of fully deleting the data should be provided and explained

**Comment by mauerbac** [comment]
Hello --

Deleted items have a TTL so that other clients can sync them down and know which records need to be deleted from their local storage. I don't think this behavior can be avoided for the sake of data integrity.

I believe by default the TTL is a month for the record to be removed from the models' DynamoDB table and 30 minutes to be removed from the Delta Sync Table.
