### ISSUE TITLE
Amazon Transcribe

### ISSUE THREAD

**Issue by ankit24x7** [aws-amplify/docs#418]
Does amazon transcribe fulfill purpose of Voice To Text (live streaming) in Android/iOS Platforms. Please revert on this asap.

**Comment by minbi** [comment]
We don't currently support this functionality. We are recording this as a feature request.

**Comment by muellerfr** [comment]
Hi @ankit24x7, we're tracking this feature request here: https://github.com/aws-amplify/aws-sdk-ios/issues/1208. Please follow the issue thread for any updates.

**Comment by craig429** [comment]
I have recently discovered Amazon Transcribe as a potential major player in the underserved hearing impaired user space, which I serve via non-profits. I am going to present the platform to our local HI users next week as a suggested adjunct to speakers/presenters in public settings. I believe this would benefit a larger population, and be less distracting than an ASL assistant signing behind someone conducting a presentation. Right now I am projecting the real-time transcription on a screen behind the speaker, but an iOS/Android solution would clearly be the next logical step in serving this community. The latency is a bit of an issue, since I currently have to use us-west-2 from my location in Berkeley, but I presume us-west-1 will eventually become available. Additional iOS/Android functionality would make Amazon heroes in the (growing) hearing impaired population in my opinion.
