### ISSUE TITLE
[Feedback]Please add "pubsub" link for AWS IoT Android SDK

### ISSUE THREAD

**Issue by leospace** [aws-amplify/docs#4214]
**Page**: [`/sdk/pubsub/getting-started/q/platform/[platform]`](https://docs.amplify.aws/sdk/pubsub/getting-started/q/platform/android)

**Feedback**:

We contact the support center because of we can not find document about AWS IoT pub/sub functions. The support center give us bellow link: https://docs.amplify.aws/sdk/pubsub/getting-started/q/platform/android/

We couldn't find this document link before, because of It is not mentioned in the README.md of Android SDK on the Github: [https://github.com/aws-amplify/aws-sdk-android/blob/main/README.md#aws-sdk-for-android ](https://github.com/aws-amplify/aws-sdk-android/blob/main/README.md#aws-sdk-for-android).
We ONLY see bellow description:  
For new projects, we recommend interacting with AWS using the [Amplify Framework](https://docs.amplify.aws/lib/q/platform/android/ ](https://docs.amplify.aws/lib/q/platform/android/).

Click the link "Amplify Framework", will go into [https://docs.amplify.aws/lib/q/platform/android/ ](https://docs.amplify.aws/lib/q/platform/android/)
Nobody can find any link to the documents the support center provided (link: https://docs.amplify.aws/sdk/pubsub/getting-started/q/platform/android/).

So we suggest you or the AWS Dev Team should add links which you provided into the README.md file or the page :[https://docs.amplify.aws/lib/q/platform/android/ ](https://docs.amplify.aws/lib/q/platform/android/).

**Comment by arundna** [comment]
@leospace 👋  Thanks for opening this issue! The link provided by support center is our docs site for Mobile SDK's and the current Amplify Libraries docs does not have the section pertaining to AWS IOT Pub/Sub. 

I'll confirm this with our team and keep you updated.

**Comment by tjleing** [comment]
The issue is that [the Amplify library docs](https://docs.amplify.aws/lib/q/platform/android/) are separate from [the Android SDK docs](https://docs.amplify.aws/sdk/q/platform/android/) -- PubSub and several other categories are only supported in the Android SDK.  There is a link in a callout on [the Amplify library docs page](https://docs.amplify.aws/lib/q/platform/android/), and from there you can see the SDK-specific categories.

This behavior is shared across iOS and Android, so I'm going to turn this into a 'docs site itself' issue.  Also @jakeburden "PubSub" is an example of text that should be showing up in the search bar but isn't.
