### ISSUE TITLE
[Feedback] Import of aws-amplify causes Expo build to fail in Fastlane

### ISSUE THREAD

**Issue by orome** [aws-amplify/docs#4304]
**Page**: [`/start/getting-started/setup/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/setup/q/integration/react-native/#install-amplify-libraries)

**Feedback**:

This does not work for Expo builds. Attempting `expo build ...` after adding 
```
import { Amplify } from 'aws-amplify'
```
results in a Fastlane build failure.

**Comment by cwomack** [comment]
Hello, @orome 👋.  Thanks for opening this issue and for your patience with us getting you a response.  I've tried walking through the steps within the React Native tutorial you've linked above, but didn't have any issues with a Fastlane build.  

Can you verify some local details such as the React Native and Amplify versions (if you haven't upgraded the app since this was opened)?  If you try the tutorial steps again and get the same results, please let us know!

**Comment by cwomack** [comment]
Closing this issue as we have not heard back from you. If you are still experiencing this, please feel free to reply back and provide any information previously requested and we'd be happy to re-open the issue.

Thank you!
