### ISSUE TITLE
NextJS Getting Started guide: **Error: No current user**

### ISSUE THREAD

**Issue by artidata** [aws-amplify/docs#4376]
**Describe the bug**
I'm trying to follow the [NextJS Getting Started Guide](https://docs.amplify.aws/start/q/integration/next/).  However, I'm now stuck at this [section](https://docs.amplify.aws/start/getting-started/data-model/q/integration/next/#api-with-server-side-rendering-ssr), with **Error: No current user** :

Someone else has reproduced the bug in [StackOverflow](https://stackoverflow.com/questions/71896524/getting-no-current-user-error-in-amplify-with-next-js).

**To Reproduce**
- Follow the [NextJS Getting Started Guide](https://docs.amplify.aws/start/q/integration/next/).
- Error should be reproduced in [Connect API and database to the app](https://docs.amplify.aws/start/getting-started/data-model/q/integration/next/).

**Expected behavior**
Tutorial can go smoothly until deploy and host app.

**Screenshots**
![Screenshot 2022-06-09 5 55 06 PM](https://user-images.githubusercontent.com/20266094/172833397-0306e0d7-2231-45fc-8c00-553400587669.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: chrome

**Comment by siegerts** [comment]
Hi @artidata , thanks for raising. I have a repo using the new Authenticator UI + Next SSR + `getServerSideProps` (https://github.com/siegerts/next-amplified/blob/main/pages/index.js) that may help to get you unblocked. The linked StackOverflow question is using `getStaticPaths` and `getStaticProps` are invoked during build time so the `user` will likely not be present since the user is not "logged in" when you run your build process.

**Comment by rachelnabors** [comment]
Between updating this tutorial and @artidata's thumbs up, I am considering this issue closed!
