### ISSUE TITLE
"+" in code snippets should not copy over

### ISSUE THREAD

**Issue by rachelnabors** [aws-amplify/docs#4667]
**Describe the bug**
Sometimes code snippets have little "+" next to lines to indicate that they've been added. But when you copy paste, they're included. This means you have to either hand-remove all the +s from your copy pasta, or you have to write it all out yourself. Neither is pleasant.

**To Reproduce**
1. Go to https://docs.amplify.aws/start/getting-started/data-model/q/integration/js/#connect-frontend-to-api
2. Scroll to the second code snippet
![Screen Shot 2022-10-06 at 12 48 51 PM](https://user-images.githubusercontent.com/236306/194405718-9bd969c9-9eb4-4d7c-84c4-aa6bb6045337.png)
4. Click "copy"
5. Paste into code editor.

And that's how you get ~ants~ +s all over, breaking your code.

**Expected behavior**
When I copy and past a code snippet, the +s should not be copied over.

**Possible solution**
In the same Markdown parsing step that turns lines with +'s green, have it remove the + sign and add a bit of CSS that adds the plus sign using `content: "+"`. This shouldn't be picked up by copy-paste procedures

**Comment by rachelnabors** [comment]
Or even finding a new way to highlight code in Markdown would be a good solution!

**Comment by annemano** [comment]
Hi!

_Disclaimer: I'm a junior dev, and new to contributing to open source in general_

I know that prism.js has a [line-highlight plugin](https://prismjs.com/plugins/line-highlight/), but it would require a refactor of all instances where you are using `diff` codeblocks, and I am personally not sure how to implement the plugin in Next.js. Someone else with experience could do it, though!

Otherwise, if you still just want to remove the +'s from the beginning of lines when copying, I could work on the issue! I haven't thought of doing it with CSS though, I was thinking of removing it at the moment we're copying it to the clipboard 🤔 While adding a "+" with CSS is easy to do, I have the impression that the Markdown parsing step you mention is handled by Prism. But I might be wrong!
