### ISSUE TITLE
Not compatible with Objective-C projects.

### ISSUE THREAD

**Issue by semionenko** [aws-amplify/docs#469]
I would like to be able to integrate without dancing with a tambourine with old projects written on Objective-C.

**Comment by kvasukib** [comment]
@semionenko Sorry for the inconvenience caused.
Can you provide more details on what are the AWS dependencies of your app?

**Comment by Stunner** [comment]
@kvasukib I don't understand why you would need those questions you asked answered of the OP in order to act on this. I am encountering this same issue 7 months later and documentation is still very lacking for Objective-C. Frustrating seeing a lack of motivation or work ethic on the documentation team's part. Sorry to say but you have lost my business as a result.
