### ISSUE TITLE
[Feedback]Recommendation unclear

### ISSUE THREAD

**Issue by hanchhanch** [aws-amplify/docs#4803]
**Page**: [`/lib/restapi/getting-started/q/platform/[platform]`](https://docs.amplify.aws/lib/restapi/getting-started/q/platform/js)

**Feedback**:

Regarding the box at the bottom "THIS IS NOT A RECOMMENDED ARCHITECTURE", it's not clear whether the recommendation refers to the last instruction or the entire page.

**Comment by nadetastic** [comment]
Hi @hanchhanch the notice refers to the last section where endpoint is set to Lambda function URL(invoking it directly), instead of leveraging AWS AppSync or API Gateway as the endpoint to invoke the Lambda function.

In short, you want to place a proxy between the client and the Lambda function, such as API Gateway.

**Comment by hanchhanch** [comment]
Makes sense. I just suggested to make it clear on the page.
Thanks

**Comment by nadetastic** [comment]
Got it @hanchhanch will clarify
