### ISSUE TITLE
Error when decoding fetched data

### ISSUE THREAD

**Issue by xavierflandro** [aws-amplify/docs#5143]
**Page**: [`/lib/restapi/fetch/q/platform/[platform]`](https://docs.amplify.aws/lib/restapi/fetch/q/platform/ios)

**Feedback**:

After following all instructions, the line: 
`let str = String(decoding: data, as: UTF8.self)`
(from the first block of the **Fetching Data** section) returns the error:
    `Initializer 'init(decoding:as:)' requires that 'C' conform to 'Collection'`

**Comment by atierian** [comment]
Thanks for opening this issue @xavierflandro.

The code snippet linked works as expected. Can you confirm that you're using v2 of Amplify Swift? If you're using v1, the `Amplify.API.get` API takes a callback rather than async / await. It could be that Xcode is presenting the error there rather than the `get` line.

<img width="757" alt="get_todo_screenshot" src="https://user-images.githubusercontent.com/52051793/229168391-2b338561-7b60-47fc-bb30-b0c4795f005c.png">
