### ISSUE TITLE
Question Does Amplify Lib support to access Amazon Workdocs ?

### ISSUE THREAD

**Issue by hansoon1** [aws-amplify/docs#5543]
Hello,

I have a question about the Amplify Lib.
Can I use the Amplify Lib to create a user-level app running in an Android environment to access Amazon WorkDocs?
Is there an equivalent to the WorkDocsClient in the AWS SDK for JAVA in the Amplify Lib?

I'm looking at the Amplify Lib because the AWS SDK for JAVA doesn't work on Android and I can't find anything about it.

**Comment by abdallahshaban557** [comment]
Hi @hansoon1  - we do not have a client for interacting with Amazon WorkDocs at this time. I would recommend that you submit a [Github issue](https://github.com/aws-amplify/amplify-js/issues/new?assignees=&labels=pending-triage&projects=&template=2.feature_request.yaml) for us to track interest from our community. I will close this issue here since this is not a documentation issue and rather a new feature request.
