### ISSUE TITLE
GraphQL API - Flutter app

### ISSUE THREAD

**Issue by M7MMAD-OMAR** [aws-amplify/docs#5554]
Welcome,

**Why when using GraphQL API in Flutter applications**
When I delete an item it is marked as deleted
But when I fetch the data, it brings me all the deleted and non-deleted data
How can I fetch non-deleted data only within Flutter ??

Thank you >>

**Comment by abdallahshaban557** [comment]
Hi @M7MMAD-OMAR - can you please give us a bit more details on how you are deleting your items, and how you are then retrieving them? I would recommend you actually open a Github issue on this repo - and provide us with reproduction steps so that we can investigate this further.

https://github.com/aws-amplify/amplify-flutter/issues/new?assignees=&labels=&projects=&template=BUG-REPORT.yaml

**Comment by M7MMAD-OMAR** [comment]
Ok thank you ,

I wrote it here,

https://github.com/aws-amplify/amplify-flutter/issues/3176

**Comment by abdallahshaban557** [comment]
Awesome! I am closing this issue then!
