### ISSUE TITLE
[Feedback]Tutorial Deploy Issues

### ISSUE THREAD

**Issue by domschwe** [aws-amplify/docs#5580]
**Page**: [`/start/getting-started/auth/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/auth/q/integration/react-native)

**Feedback**:

Hi, I just tried following the tutorial, and everything worked up until I deployed. When I navigated to the URL, I received a "AccessDenied" error, and based on some research it looks like this might be because of the build settings. Could you please include some guidance on which settings to update so that the whole tutorial deploys properly? 
<img width="880" alt="image" src="https://github.com/aws-amplify/docs/assets/8878885/0ddc42c3-6187-4323-b97c-7d9634e545af">

**Comment by Jay2113** [comment]
Hi @domschwe 👋 , thanks for raising this with us!

The following `getting started` guides do include troubleshooting steps in regards to the `AccessDenied` error:
- https://docs.amplify.aws/start/getting-started/hosting/q/integration/react/#publish-your-app
- https://docs.amplify.aws/start/getting-started/hosting/q/integration/angular/#publish-your-app
- https://docs.amplify.aws/start/getting-started/hosting/q/integration/vue/#publish-your-app

```
You may get an "AccessDenied" error if your app's distribution directory is not set properly. 
To fix this, change the distribution directory via amplify configure project and then re-run amplify publish.
```

I hope this information helps unblock your deployments and please let us know if you are still blocked due to this error.
