### ISSUE TITLE
Typo on function build option pages

### ISSUE THREAD

**Issue by SalmonMode** [aws-amplify/docs#5785]
**Describe the content issue**:
The function build option page has the following sentence at the top of the page:

```
amplify push will look for a script definition in the project root's package.json with the name amplify:<resource_name> and run it right after npm install is canned in the function resource's src directory.
```

But I believe it should be "called" instead of "canned".

**URL page where content issue is**:
https://docs.amplify.aws/cli/function/build-options/

**Comment by timngyn** [comment]
👋 Hi @SalmonMode, I think your PR is pointing to the wrong base branch. If you can switch it over to `aws-amplify/docs` then we can get it reviewed and merge! Should be quick since it's just a typo fix. Thank you for bring it up!

Switching the base branch: https://github.blog/2016-08-15-change-the-base-branch-of-a-pull-request/

**Comment by SalmonMode** [comment]
Oh woops, haha! Thanks for the heads up! I'll fix that now

**Comment by timngyn** [comment]
Thanks again @SalmonMode! Your fix should be live now! (going to close the issue)
