### ISSUE TITLE
[missing-page] it is the link form amplify studio

### ISSUE THREAD

**Issue by peter-iglaev** [aws-amplify/docs#6670]
**Page**: [`https://docs.amplify.aws/lib/restapi/getting-started/`](https://docs.amplify.aws/lib/restapi/getting-started/)

**Feedback**: <!-- your feedback here  */}

**Comment by timngyn** [comment]
Hi @peter-iglaev, thank you so much for opening the issue. We've set up a redirect to this page: https://docs.amplify.aws/react/build-a-backend/restapi/configure-rest-api/

I'm going to close out this issue since this is fixed now. Please feel free to open another one if you find any more broken links.
