### ISSUE TITLE
AWS amplify reference API link missing

### ISSUE THREAD

**Issue by AurelienLW** [aws-amplify/docs#678]
**Describe the bug**
The link at the end is sending the user to a 404 error page not found

**To Reproduce**
When you are on that link, go to the end of the page, click API reference
https://aws-amplify.github.io/docs/js/interactions

link that isn't working : https://aws-amplify.github.io/docs/api/classes/interactions.html
**Expected behavior**
The link should work

**Screenshots**
![image](https://user-images.githubusercontent.com/46943114/57623184-8bef4e00-758f-11e9-87cc-d8553c2f16db.png)

**Desktop:**
Win10 Family
Chrome

**Comment by jpl154** [comment]
**Describe the bug**
Your /docs/*  pages are returning a 404 error.

**To Reproduce**
Escalating previous behavior.  Attempt to click any link off the the (https://aws-amplify.github.io/docs/) domain

**Expected behavior**
The page should resolve the Markdown.

Screenshots
<img width="1678" alt="Screen Shot 2019-05-16 at 2 53 14 PM" src="https://user-images.githubusercontent.com/5827595/57879433-79bd1c00-77ea-11e9-96a8-58c17a483b4e.png">
<img width="1677" alt="Screen Shot 2019-05-16 at 2 53 00 PM" src="https://user-images.githubusercontent.com/5827595/57879449-83468400-77ea-11e9-93c8-1743a96f588b.png">


Desktop:
Mac
Firefox

**Comment by jpl154** [comment]
Looks like a similar issue is getting traction Ref: #683

**Comment by kaustavghosh06** [comment]
Hey guys, I beleive GitHub fixed the issue from their issue and I was able to access the pages back again :)
